import type { Metadata } from "next";
import "./globals.css"
import localFont from 'next/font/local'
import Navbar from "@/components/layout/Navbar";



const satoshi = localFont({
  src: [
    { path: './fonts/Satoshi-Regular.otf', weight: '400' },
    { path: './fonts/Satoshi-Medium.otf', weight: '500' },
    { path: './fonts/Satoshi-Bold.otf', weight: '700' },
  ],
  variable: '--font-satoshi',
})


export const metadata: Metadata = {
  title: "Trukka Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={` ${satoshi.variable} h-screen overflow-hidden antialiased`}
    >
      <body className="font-satoshi">
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
